// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAM3CCZSYCP3gdEy4rt_sV6QpUo91JJjOY',
    appId: '1:745761092564:web:fcda89ec2d73fdc6691c41',
    messagingSenderId: '745761092564',
    projectId: 'walltutorial-eee9e',
    authDomain: 'walltutorial-eee9e.firebaseapp.com',
    storageBucket: 'walltutorial-eee9e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRmMegFii_QrIEguqVxqTL4bB0EHU2YmM',
    appId: '1:745761092564:android:7e89534520cb069d691c41',
    messagingSenderId: '745761092564',
    projectId: 'walltutorial-eee9e',
    storageBucket: 'walltutorial-eee9e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQkpLVvLgwenm_oMweD18REMq-eo-DuIk',
    appId: '1:745761092564:ios:02532e1c2a5b04dd691c41',
    messagingSenderId: '745761092564',
    projectId: 'walltutorial-eee9e',
    storageBucket: 'walltutorial-eee9e.appspot.com',
    iosBundleId: 'com.example.socialweb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQkpLVvLgwenm_oMweD18REMq-eo-DuIk',
    appId: '1:745761092564:ios:857823ccc1184974691c41',
    messagingSenderId: '745761092564',
    projectId: 'walltutorial-eee9e',
    storageBucket: 'walltutorial-eee9e.appspot.com',
    iosBundleId: 'com.example.socialweb.RunnerTests',
  );
}
